[package]
name = "dioxus-static-site-generation"
authors = ["Evan Almloff"]
version = { workspace = true }
edition = "2021"
description = "Static site generation for Dioxus"
license = "MIT OR Apache-2.0"
repository = "https://github.com/DioxusLabs/dioxus/"
homepage = "https://dioxuslabs.com"
keywords = ["ui", "gui", "react", "ssg"]
resolver = "2"

[dependencies]
dioxus-fullstack = { workspace = true }
dioxus-lib.workspace = true
dioxus-router = { workspace = true }
dioxus-ssr = { workspace = true, optional = true }
dioxus-isrg = { workspace = true, optional = true }
dioxus-devtools = { workspace = true, optional = true }
dioxus-web = { workspace = true, optional = true, features = ["hydrate"]}

axum = { workspace = true, optional = true, features = ["ws", "macros"]}
tower = { workspace = true, optional = true, features = ["util"]}
tower-http = { workspace = true, optional = true, features = ["fs"]}
tokio = { workspace = true, optional = true }
http = { workspace = true, optional = true }
tracing = { workspace = true }

[dev-dependencies]
dioxus = { workspace = true }
criterion = { workspace = true }

[features]
default = []
server = [
    "dioxus-fullstack/server",
    # "dioxus-router/ssr",
    "dep:dioxus-ssr",
    "dep:tokio",
    "dep:http",
    "dep:axum",
    "dep:tower-http",
    "dep:dioxus-devtools",
    "dep:tower",
]
# server = ["dioxus-fullstack/server", "dioxus-router/ssr", "dep:dioxus-ssr", "dep:tokio", "dep:http", "dep:axum", "dep:tower-http", "dep:dioxus-hot-reload", "dep:dioxus-cli-config", "dep:tower"]
web = ["dep:dioxus-web"]
# web = ["dioxus-fullstack/web", "dep:dioxus-web"]
# web = ["dioxus-fullstack/web", "dioxus-router/web", "dep:dioxus-web"]

# [[bench]]
# name = "incremental"
# required-features = ["server"]
# harness = false

[package.metadata.docs.rs]
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples"]
